name: devin
version: 1.0.0
synopsis: Devin programming language
category: Language
author: Matteo Morena

default-extensions:
  # GHC2021
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - GADTSyntax
  - GeneralizedNewtypeDeriving
  - HexFloatLiterals
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances

  # Syntax
  - LambdaCase
  - BlockArguments

  # Types
  - TypeFamilies
  - DataKinds

  # Records
  - DuplicateRecordFields

  # Class and instances declarations
  - UndecidableInstances

  # Literals
  - OverloadedStrings
  - OverloadedLabels

  # Bang patterns and Strict Haskell
  - Strict

ghc-options:
  - -O2
  - -foptimal-applicative-do
  - -fplugin=RecordDotPreprocessor
  - -Wall
  - -Wno-name-shadowing
  - -Wno-type-defaults
  - -Wno-unused-do-bind

dependencies:
  - base
  - bytestring
  - text
  - containers
  - transformers
  - haskell-gi-base
  - gi-glib
  - gi-gio
  - gi-gtk
  - gi-gtk-hs
  - gi-gtksource
  - record-hasfield
  - record-dot-preprocessor

library:
  source-dirs: src

  exposed-modules:
    - CallTarget
    - Main
    - Parser
    - Parser.Input
    - Parser.Result
    - Parsers
    - Span
    - Syntax
    - Type
    - Typer
    - Typer.Environment
    - Typer.Error
    - Typers

executables:
  devin:
    main: Main.hs
    source-dirs: app
    default-extensions: PackageImports
    ghc-options: -threaded
    dependencies: devin

tests:
  devin-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wno-orphans
    build-tools: hspec-discover:hspec-discover

    dependencies:
      - QuickCheck
      - quickcheck-instances
      - checkers
      - hspec
      - hspec-checkers
      - devin
