name: devin
version: 1.0.0
synopsis: Devin programming language
category: Language
author: Matteo Morena

default-extensions:
  # GHC2021
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - GADTSyntax
  - GeneralizedNewtypeDeriving
  - HexFloatLiterals
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances

  # Syntax
  - ApplicativeDo

  # Types
  - TypeFamilies
  - DataKinds

  # Records
  - DuplicateRecordFields

  # Class and instances declarations
  - UndecidableInstances

  # Literals
  - OverloadedStrings

ghc-options:
  # Warnings
  - -Wall
  - -Wno-name-shadowing
  - -Wno-type-defaults
  - -Wno-unused-do-bind

  # Optimisation levels
  - -O2

  # Individual optimisations
  - -foptimal-applicative-do

dependencies: base

library:
  source-dirs: src

  exposed-modules:
    - CallTarget
    - Evaluator
    - Evaluator.State
    - Evaluator.Configuration
    - Evaluators
    - Main
    - Parser
    - Parser.Input
    - Parser.Result
    - Parsers
    - Range
    - Syntax
    - Type
    - Typer
    - Typer.Environment
    - Typer.Error
    - Typers
    - Value

  dependencies:
    - extra
    - text
    - containers
    - transformers
    - haskell-gi-base
    - gi-glib
    - gi-gio
    - gi-gtk
    - gi-gtk-hs
    - gi-gtksource
    - record-hasfield
    - record-dot-preprocessor
  
  ghc-options: -fplugin=RecordDotPreprocessor

executables:
  devin:
    main: Main.hs
    source-dirs: app
    default-extensions: PackageImports
    ghc-options: -threaded
    dependencies: devin
