name: devin
version: 1.0.0
synopsis: Devin programming language
category: Language
author: Matteo Morena

default-extensions:
  # Syntax
  - ApplicativeDo
  - TupleSections
  - LambdaCase
  - BlockArguments

  # Types
  - GADTs
  - DataKinds
  - TypeApplications

  # Records
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - NamedFieldPuns
  - RecordWildCards

  # Deriving mechanism
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable

  # Class and instances declarations
  - MultiParamTypeClasses
  - FlexibleInstances
  - UndecidableInstances

  # Literals
  - NegativeLiterals
  - OverloadedStrings
  - OverloadedLabels

  # Type signatures
  - ExplicitForAll
  - ScopedTypeVariables

  # Bindings and generalisation
  - NoMonomorphismRestriction

ghc-options:
  - -O2
  - -foptimal-applicative-do
  - -fplugin=RecordDotPreprocessor
  - -Wall
  - -Wno-name-shadowing
  - -Wno-type-defaults
  - -Wno-unused-do-bind

dependencies:
  - base
  - text
  - containers
  - transformers
  - record-hasfield
  - record-dot-preprocessor
  - haskell-gi-base
  - gi-glib
  - gi-gio
  - gi-gtk
  - gi-gtk-hs
  - gi-gtksource

library:
  source-dirs: src

  exposed-modules:
    - Input
    - Main
    - Parser
    - Parsers
    - Result
    - Span
    - Syntax
    - Type

executables:
  devin:
    main: Main.hs
    source-dirs: app
    default-extensions: PackageImports
    ghc-options: -threaded
    dependencies: devin

tests:
  devin-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wno-orphans
    build-tools: hspec-discover:hspec-discover

    dependencies:
      - QuickCheck
      - quickcheck-instances
      - checkers
      - hspec
      - hspec-checkers
      - devin
