name: devin
version: 1.0.0
synopsis: Devin programming language
category: Language
author: Matteo Morena

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-type-defaults
  - -Wno-unused-do-bind
  - -O2
  - -foptimal-applicative-do

default-extensions:
  # Syntax
  - ApplicativeDo
  - LambdaCase

  # Types
  - GADTs

  # Records
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - NamedFieldPuns

  # Deriving mechanism
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable

  # Literals
  - NegativeLiterals
  - OverloadedStrings
  - OverloadedLabels

  # Bindings and generalisation
  - NoMonomorphismRestriction

dependencies:
  - base
  - transformers
  - text
  - haskell-gi-base
  - gi-glib
  - gi-gio
  - gi-gtk
  - gi-gtk-hs
  - gi-gtksource

library:
  source-dirs: src

executables:
  devin:
    main: Main.hs
    source-dirs: app

    ghc-options:
      - -threaded

    default-extensions:
      - PackageImports

    dependencies:
      - devin

tests:
  devin-test:
    main: Spec.hs
    source-dirs: test

    dependencies:
      - devin
